version: "3.9"
services:
  citydb:
    build:
      context: dbcity
      dockerfile: Dockerfile
    container_name: citydatabase
    networks:
      - api-network
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_SCHEMA}