version: "3.9"
networks:
  api-network:
    driver: bridge

services:
  citydb:
    image: ghcr.io/knottem/weatherapi-db:1.0
    container_name: citydatabase
    networks:
      - api-network
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_SCHEMA}
    healthcheck:
      test: ["CMD-SHELL", "mysql -u${DB_USER} -p${DB_PASSWORD} ${DB_SCHEMA} -e 'SELECT 1'"]
      interval: 20s
      timeout: 10s
      retries: 3

  weatherapi:
    build:
      dockerfile: Dockerfile
    container_name: apiweather
    networks:
      - api-network
    ports:
      - "8080:8080"
    depends_on:
      citydb:
        condition: service_healthy
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_HOST=citydatabase
      - DB_PORT=3306
      - CACHE_TIME_IN_HOURS=${CACHE_TIME_IN_HOURS}
      - DOMAIN=${DOMAIN}
      - GITHUB=${GITHUB}
    volumes:
      - gradle-cache:/root/.gradle
      - gradle-wrapper-cache:/app/gradle/wrapper
      - ./weatherapi:/app

volumes:
  gradle-cache:
  gradle-wrapper-cache: