version: "3.9"

services:
  citydb:
    image: ghcr.io/knottem/weatherapi-db:latest
    container_name: citydatabase
    networks:
      - api-network
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_SCHEMA}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    healthcheck:
      test: ["CMD-SHELL", "mysql -u${DB_USER} -p${DB_PASSWORD} ${DB_SCHEMA} -e 'SELECT 1'"]
      interval: 20s
      timeout: 10s
      retries: 3

  weatherapi:
    image: ghcr.io/knottem/weatherapi:latest
    container_name: apiweather
    networks:
      - api-network
    ports:
      - "8080:8080"
    depends_on:
      citydb:
        condition: service_healthy
    environment:
      - DB_HOST=citydb
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SCHEMA=${DB_SCHEMA}
      - CACHE_TIME_IN_HOURS=${CACHE_TIME_IN_HOURS}
      - DOMAIN=${DOMAIN}
      - GITHUB=${GITHUB}

networks:
  api-network:
    driver: bridge